version: '3'

services: 
  
  kyopurorecordapp:
    container_name: 'kyopurorecordapp'
    build:
      context: './'
      dockerfile: 'Dockerfile'
    volumes: 
      - './api:/code/api'
    ports: 
      - '80:80'
    depends_on:
      - mysql
    command: ["uvicorn", "api.crud:app", "--host", "localhost", "--port", "80"]
    networks:
      - my_network

  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: db
      MYSQL_PASSWORD: password
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    networks:
     - my_network

networks:
  my_network:
    driver: bridge